---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aliyun-rds-exporter
  name: aliyun-rds-exporter-service
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 5234
    protocol: TCP
    targetPort: 5234
  selector:
    app: aliyun-rds-exporter
  type: ClusterIP
---